apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: github-follower-bot-egress
spec:
  podSelector:
    matchLabels:
      app: github-follower-bot
  policyTypes:
    - Egress
  egress:
    - to:
        - namespaceSelector: {}
      ports:
        - protocol: TCP
          port: 443
