"""Domain-level contracts for application use-cases and persistence adapters."""

from __future__ import annotations

from typing import Protocol, runtime_checkable


class RunExecutor(Protocol):
    """Contract for a component that can execute one bot run."""

    def run(self) -> dict:
        """Execute a full run and return a structured summary payload."""


@runtime_checkable
class StoragePort(Protocol):
    """Persistence contract used by runtime and CLI commands."""

    def close(self) -> None: ...
    def commit(self) -> None: ...
    def begin_run(self, trace_id: str) -> int: ...
    def finish_run(self, run_id: int, followers_fetched: int, followers_followed: int, error_message: str | None) -> None: ...
    def upsert_follower_seen(self, username: str) -> None: ...
    def is_followed(self, username: str) -> bool: ...
    def has_successful_follow_action(self, username: str) -> bool: ...
    def mark_followed(self, username: str) -> None: ...
    def add_follow_action(
        self,
        run_id: int,
        username: str,
        success: bool,
        status_code: int | None,
        error_message: str | None,
        discovery_context: dict[str, object] | None = None,
    ) -> None: ...
    def add_security_event(self, event: str, details: str | None, run_id: int | None = None) -> None: ...
    def add_rate_limit_snapshot(self, run_id: int, remaining: int | None, reset_at: int | None) -> None: ...
    def upsert_repository_catalog_entry(
        self,
        *,
        full_name: str,
        owner_login: str,
        repo_name: str,
        is_fork: bool,
        parent_full_name: str | None,
        source_root_full_name: str | None,
        repo_updated_at: str | None,
        stargazers_count: int | None,
        forks_count: int | None,
        watchers_count: int | None,
        open_issues_count: int | None,
        language: str | None,
        default_branch: str | None,
        archived: bool | None,
        disabled: bool | None,
        pushed_at: str | None,
        last_forked_at: str | None,
        last_fork_status: str | None,
        last_fork_error: str | None,
    ) -> None: ...
    def upsert_follow_job(self, run_id: int, username: str, status: str, error_message: str | None = None, increment_attempt: bool = False) -> None: ...
    def get_follow_job_stats(self, run_id: int | None = None) -> dict[str, int]: ...
    def fetch_follow_jobs(self, run_id: int, statuses: tuple[str, ...] = ("pending",), limit: int = 100) -> list[dict]: ...
    def get_follow_job(self, run_id: int, username: str) -> dict | None: ...
    def get_run(self, run_id: int) -> dict | None: ...
    def abort_run(self, run_id: int, reason: str) -> bool: ...
    def set_setting(self, key: str, value: str) -> None: ...
    def get_setting(self, key: str) -> str | None: ...
    def try_acquire_distributed_lock(self, lock_key: str, lock_until_epoch: int, now_epoch: int) -> bool: ...
    def release_distributed_lock(self, lock_key: str, expected_lock_until_epoch: int) -> bool: ...
    def get_stats(self) -> dict[str, int]: ...
    def get_last_run(self) -> dict | None: ...
    def export_recent_audit(self, limit: int = 200) -> dict: ...
    def export_prometheus_metrics(self) -> str: ...
    def export_postgres_migration_profile(self) -> dict: ...
    def export_sbom(self) -> dict: ...
    def export_release_manifest(self, signing_key: str | None = None) -> dict: ...
    def verify_release_manifest(self, manifest_path: str, signing_key: str | None = None, require_signature: bool = False, max_age_seconds: int | None = None) -> dict: ...
    def get_table_counts(self, table_names: list[str]) -> dict[str, int]: ...
    def check_connection(self) -> tuple[bool, str]: ...
    def db_integrity_status(self) -> str: ...
    def get_schema_version(self) -> str: ...
    def storage_adapter_name(self) -> str: ...
